<?php
namespace Battleships\Model\Game\Battleships;

/**
 * This is the class that every action instance should return as a result
 * Class ActionResult
 * @package Battleships\Model\Game\Battleships
 */
class ActionResult
{
    private $success;
    private $resultValue;

    public function __construct($success, $resultValue)
    {
        $this->success = $success;
        $this->resultValue = $resultValue;
    }

    /**
     * Check if the action that was performed is successful
     * @return mixed
     */
    public function success()
    {
        return $this->success;
    }

    /**
     * Get the data generated by the action
     * @return mixed
     */
    public function getValue()
    {
        return $this->resultValue;
    }
}